# Generated by Django 5.1.3 on 2025-01-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='min_order_quantity',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='price_retail',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='price_wholesale',
        ),
    ]
