# Generated by Django 5.1.3 on 2024-12-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
