# Generated by Django 5.1.3 on 2024-12-14 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_orderitem_supplier_product_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_supplier', to='products.supplier'),
        ),
    ]
